apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale
  labels:
    app: app
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: autoscale
  template:
    metadata:
      labels:
        app: autoscale
    spec: 
      containers:
        - name: apache
          image: httpd:2.4.62
          ports:
            - containerPort: 80
