---
- name: Install nginx
  hosts: all
  gather_facts: true
  become: yes
  tasks:
  - name: Install nginx RedHat family
    dnf:
      name: 
        - nginx
      state: present
    when: ansible_os_family=="RedHat"

  - name: Install nginx Debian family
    apt:
      name:
        - nginx
      state: present
    when: ansible_os_family=="Debian"
