apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-task
  labels:
    app : {{.Release.Name}}task
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      project: {{.Release.Name}}
  template:
    metadata:
      labels:
        project: {{.Release.Name}}  
    spec:
      containers:
        - name : {{.Release.Name}}-web
          image: {{.Values.container.image}}
          ports:
            - containerPort: 80
