stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: "inkogolik/my-lambda-app"
  IMAGE_TAG: "${CI_COMMIT_TAG:-latest}"
  HELM_RELEASE_NAME: "lambda-app"
  HELM_CHART_PATH: "helm/lambda-chart"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
  artifacts:
    paths:
      - docker-image.tar


push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - helm upgrade --install $HELM_RELEASE_NAME $HELM_CHART_PATH --set image.repository=$IMAGE_NAME,image.tag=$IMAGE_TAG
