apiVersion: v2
name: App-HelmChart
desription: My helm chart for kuber
version: 0.1.0
appVersion: "1.2.3"

keywords:
  - apache
  - http
  - https

maintainers:
  - name: Stepan
    email: stepanstepan082@gmail.com
    urt: www.example.com